// AppMessage attributes keys
enum {
  APPMESSAGE_KEY_ROUTESTEP_INDEX,
  APPMESSAGE_KEY_ROUTESTEP_DISTANCE,
  APPMESSAGE_KEY_ROUTESTEP_INSTRUCTIONS,
};

// AppMessage action keys
enum {
  APPMESSAGE_REQUEST_ROUTE,
};

